<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="KISHORE-RYALA" failures="1" tests="5" name="Personal Loan" time="0.217" errors="0" timestamp="2023-02-08T16:23:07 EST">
  <testcase classname="test.Day1" name="Demo" time="0.053">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.Demo(Day1.java:18)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Day2" name="Demo3" time="0.005"/>
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.006"/>
  <testcase classname="test.Day4" name="MobileloginHomeLoan" time="0.005"/>
  <testcase classname="test.Day4" name="WebloginHomeLoan" time="0.009"/>
  <testcase classname="test.Day1" name="Demo1" time="0.0">
    <ignored/>
  </testcase> <!-- Demo1 -->
</testsuite> <!-- Personal Loan -->
