<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-06T11:46:31 EST" name="Default suite" finished-at="2023-03-06T11:46:32 EST" duration-ms="38">
    <groups>
    </groups>
    <test started-at="2023-03-06T11:46:31 EST" name="Default test" finished-at="2023-03-06T11:46:32 EST" duration-ms="38">
      <class name="test.Day1">
        <test-method signature="Demo()[pri:0, instance:test.Day1@732c2a62]" started-at="2023-03-06T11:46:31 EST" name="Demo" finished-at="2023-03-06T11:46:31 EST" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.Day1.Demo(Day1.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Demo -->
        <test-method signature="Demo1()[pri:0, instance:test.Day1@732c2a62]" started-at="2023-03-06T11:46:32 EST" name="Demo1" finished-at="2023-03-06T11:46:32 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Demo1 -->
        <test-method is-config="true" signature="lastexecution()[pri:0, instance:test.Day1@732c2a62]" started-at="2023-03-06T11:46:32 EST" name="lastexecution" finished-at="2023-03-06T11:46:32 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastexecution -->
        <test-method is-config="true" signature="afsuite()[pri:0, instance:test.Day1@732c2a62]" started-at="2023-03-06T11:46:32 EST" name="afsuite" finished-at="2023-03-06T11:46:32 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afsuite -->
      </class> <!-- test.Day1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
